### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by flybirdxx** [christian-byrne/img2txt-comfyui-nodes#7] opened 2024-08-05 16:55 UTC
![image](https://github.com/user-attachments/assets/c46095f2-24fd-4a01-a9ab-88561e0a8473)
I got an error. Is this a new bug

**Comment by flybirdxx** [comment] 2024-08-05 16:56
This error only occurs only when using the MIniCPM model

**Comment by christian-byrne** [comment] 2024-08-09 02:09
Thank you for reporting this.

Pinning MiniCPM to old commits doesn't seem to fix it, so it's probably caused by a ComfyUI update somehow.

I will fix it this weekend.

**Comment by christian-byrne** [comment] 2024-08-09 11:23
Fixed in 0c5bc264b617f0865af44132cd914b69caa0cde2.

The issue is MiniCPM is not compatible with `transformers` 4.42.0 update. The newest version of transformers that is compatible is 4.41.2. 

You can either update this node through the manager or simply just run:

```bash
pip install transformers==4.41.2
```

Reference:

- OpenBMB/MiniCPM-V#357

**Closed by christian-byrne** 2024-08-09 11:23 UTC
